added discussionId in ReportDiscussionCommentDetails.js
CodeTrophs/Backend pull request #132
Opened 2020-12-02 18:49 UTC by ankitvashisht12

2020-12-03 15:22 UTC, Dishebh requested changes

2020-12-03 15:22 UTC, Dishebh commented on src/models/ReportDiscussionCommentDetails.js
> +    },
Add `ref` to `Discussion` model.

2020-12-03 16:03 UTC, ankitvashisht12 commented on src/models/ReportDiscussionCommentDetails.js
> +    },
sure

2020-12-03 17:11 UTC, Dishebh commented on src/models/ReportDiscussionCommentDetails.js
> +    },
Please move this block of code below the `userId`

2020-12-04 14:12 UTC, ankitvashisht12 commented on src/models/ReportDiscussionCommentDetails.js
> +    },
sure

2020-12-05 07:38 UTC, Dishebh approved these changes

2020-12-05 07:38 UTC, merged